"""initial schema

The tables come straight from the ORM metadata. For the first migration of a project that
has no installed base, a hand-transcribed copy of the models is a second source of truth
that can only ever drift; later migrations are ordinary autogenerated diffs against it.

Revision ID: 0001
"""
from alembic import op

from ragb.models import Base

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

EXTENSIONS = (
    "vector",     # pgvector: the embedding columns and their HNSW indexes
    "pg_trgm",    # trigram similarity: the Korean substring leg and the path leg
    "citext",     # case-insensitive email
)


def upgrade() -> None:
    conn = op.get_bind()
    for ext in EXTENSIONS:
        conn.exec_driver_sql(f'CREATE EXTENSION IF NOT EXISTS "{ext}"')
    Base.metadata.create_all(bind=conn)


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
